"""Add ledger tables

Revision ID: 0211754d932b
Revises: ea498cf1cc5a
Create Date: 2026-07-17 09:37:48.935018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0211754d932b'
down_revision: Union[str, Sequence[str], None] = 'ea498cf1cc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_ledger_entries',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('monnify_transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_ledger_entries_group_id'), 'group_ledger_entries', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_ledger_entries_id'), 'group_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_group_ledger_entries_member_id'), 'group_ledger_entries', ['member_id'], unique=False)
    op.create_index(op.f('ix_group_ledger_entries_monnify_transaction_reference'), 'group_ledger_entries', ['monnify_transaction_reference'], unique=True)
    op.create_table('wallet_ledger_entries',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('related_group_id', sa.String(), nullable=True),
    sa.Column('related_contribution_id', sa.String(), nullable=True),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_ledger_entries_id'), 'wallet_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_related_group_id'), 'wallet_ledger_entries', ['related_group_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_user_id'), 'wallet_ledger_entries', ['user_id'], unique=False)
    op.drop_index(op.f('ix_transactions_group_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('narration', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('transactions_group_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_group_id'), 'transactions', ['group_id'], unique=False)
    op.drop_index(op.f('ix_wallet_ledger_entries_user_id'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_related_group_id'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_id'), table_name='wallet_ledger_entries')
    op.drop_table('wallet_ledger_entries')
    op.drop_index(op.f('ix_group_ledger_entries_monnify_transaction_reference'), table_name='group_ledger_entries')
    op.drop_index(op.f('ix_group_ledger_entries_member_id'), table_name='group_ledger_entries')
    op.drop_index(op.f('ix_group_ledger_entries_id'), table_name='group_ledger_entries')
    op.drop_index(op.f('ix_group_ledger_entries_group_id'), table_name='group_ledger_entries')
    op.drop_table('group_ledger_entries')
    # ### end Alembic commands ###
