"""add_next_payout_date_and_time

Revision ID: 2cf2c045d40e
Revises: c7e595e7da3c
Create Date: 2026-07-18 14:32:55.286987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf2c045d40e'
down_revision: Union[str, Sequence[str], None] = 'c7e595e7da3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('next_payout_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('groups', sa.Column('payout_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'payout_time')
    op.drop_column('groups', 'next_payout_date')
    # ### end Alembic commands ###
