"""Add chat message edit delete flags

Revision ID: 3a731e25adbb
Revises: 0efe42658932
Create Date: 2026-07-18 22:30:10.046020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a731e25adbb'
down_revision: Union[str, Sequence[str], None] = '0efe42658932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chat_messages', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_deleted')
    op.drop_column('chat_messages', 'is_edited')
    # ### end Alembic commands ###
