"""Remove shortfall_policy

Revision ID: 5846dcb33bf5
Revises: be46bb563940
Create Date: 2026-07-18 21:43:32.411185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5846dcb33bf5'
down_revision: Union[str, Sequence[str], None] = 'be46bb563940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'shortfall_policy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('shortfall_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
