"""Add monnify payment tracking

Revision ID: 5c82b94849df
Revises: 0211754d932b
Create Date: 2026-07-17 10:20:15.538390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c82b94849df'
down_revision: Union[str, Sequence[str], None] = '0211754d932b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_ledger_entries', sa.Column('monnify_payment_reference', sa.String(length=255), nullable=True))
    op.add_column('wallet_ledger_entries', sa.Column('monnify_transaction_reference', sa.String(length=255), nullable=True))
    op.add_column('wallet_ledger_entries', sa.Column('monnify_payment_reference', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_wallet_ledger_entries_monnify_transaction_reference'), 'wallet_ledger_entries', ['monnify_transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_ledger_entries_monnify_transaction_reference'), table_name='wallet_ledger_entries')
    op.drop_column('wallet_ledger_entries', 'monnify_payment_reference')
    op.drop_column('wallet_ledger_entries', 'monnify_transaction_reference')
    op.drop_column('group_ledger_entries', 'monnify_payment_reference')
    # ### end Alembic commands ###
