"""Add reminder tracking table

Revision ID: 7bbf5ddfdc33
Revises: 3a731e25adbb
Create Date: 2026-07-18 23:06:14.448517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbf5ddfdc33'
down_revision: Union[str, Sequence[str], None] = '3a731e25adbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_tracking',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_tracking_group_id'), 'reminder_tracking', ['group_id'], unique=False)
    op.create_index(op.f('ix_reminder_tracking_id'), 'reminder_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_tracking_user_id'), 'reminder_tracking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_tracking_user_id'), table_name='reminder_tracking')
    op.drop_index(op.f('ix_reminder_tracking_id'), table_name='reminder_tracking')
    op.drop_index(op.f('ix_reminder_tracking_group_id'), table_name='reminder_tracking')
    op.drop_table('reminder_tracking')
    # ### end Alembic commands ###
