"""Add avatar and chat images

Revision ID: 7d911a4d04dc
Revises: c9cf5ffeb7d9
Create Date: 2026-07-19 10:02:28.493683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d911a4d04dc'
down_revision: Union[str, Sequence[str], None] = 'c9cf5ffeb7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('chat_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.alter_column('chat_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chat_messages', 'image_url')
    # ### end Alembic commands ###
