"""Move risk score to user

Revision ID: b12d380faf48
Revises: 2cf2c045d40e
Create Date: 2026-07-18 21:15:17.400150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12d380faf48'
down_revision: Union[str, Sequence[str], None] = '2cf2c045d40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'risk_score')
    op.add_column('users', sa.Column('risk_score', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('users', sa.Column('risk_factors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'risk_factors')
    op.drop_column('users', 'risk_score')
    op.add_column('memberships', sa.Column('risk_score', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
