"""Add GroupInvite model

Revision ID: bca264254b13
Revises: cac1a4782411
Create Date: 2026-07-17 08:43:37.605331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca264254b13'
down_revision: Union[str, Sequence[str], None] = 'cac1a4782411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invites',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('invited_user_id', sa.String(), nullable=False),
    sa.Column('invited_by_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_invites_group_id'), 'group_invites', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_invites_id'), 'group_invites', ['id'], unique=False)
    op.create_index(op.f('ix_group_invites_invited_user_id'), 'group_invites', ['invited_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_invites_invited_user_id'), table_name='group_invites')
    op.drop_index(op.f('ix_group_invites_id'), table_name='group_invites')
    op.drop_index(op.f('ix_group_invites_group_id'), table_name='group_invites')
    op.drop_table('group_invites')
    # ### end Alembic commands ###
