"""Remove payout_day_override

Revision ID: be46bb563940
Revises: b12d380faf48
Create Date: 2026-07-18 21:38:59.040649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be46bb563940'
down_revision: Union[str, Sequence[str], None] = 'b12d380faf48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'payout_day_override')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('payout_day_override', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
