"""Add cycle and notification models

Revision ID: c7e595e7da3c
Revises: 5c82b94849df
Create Date: 2026-07-18 09:27:14.917723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e595e7da3c'
down_revision: Union[str, Sequence[str], None] = '5c82b94849df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_assignments',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('assigned_member_id', sa.String(), nullable=False),
    sa.Column('actual_recipient_id', sa.String(), nullable=False),
    sa.Column('delegation_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actual_recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_assignments_actual_recipient_id'), 'cycle_assignments', ['actual_recipient_id'], unique=False)
    op.create_index(op.f('ix_cycle_assignments_assigned_member_id'), 'cycle_assignments', ['assigned_member_id'], unique=False)
    op.create_index(op.f('ix_cycle_assignments_group_id'), 'cycle_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_cycle_assignments_id'), 'cycle_assignments', ['id'], unique=False)
    op.create_table('delegation_requests',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('from_member_id', sa.String(), nullable=False),
    sa.Column('to_member_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_member_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegation_requests_group_id'), 'delegation_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_delegation_requests_id'), 'delegation_requests', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('swap_requests',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('initiator_member_id', sa.String(), nullable=False),
    sa.Column('target_member_id', sa.String(), nullable=False),
    sa.Column('initiator_cycle_number', sa.Integer(), nullable=False),
    sa.Column('target_cycle_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_member_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swap_requests_group_id'), 'swap_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_swap_requests_id'), 'swap_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swap_requests_id'), table_name='swap_requests')
    op.drop_index(op.f('ix_swap_requests_group_id'), table_name='swap_requests')
    op.drop_table('swap_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_delegation_requests_id'), table_name='delegation_requests')
    op.drop_index(op.f('ix_delegation_requests_group_id'), table_name='delegation_requests')
    op.drop_table('delegation_requests')
    op.drop_index(op.f('ix_cycle_assignments_id'), table_name='cycle_assignments')
    op.drop_index(op.f('ix_cycle_assignments_group_id'), table_name='cycle_assignments')
    op.drop_index(op.f('ix_cycle_assignments_assigned_member_id'), table_name='cycle_assignments')
    op.drop_index(op.f('ix_cycle_assignments_actual_recipient_id'), table_name='cycle_assignments')
    op.drop_table('cycle_assignments')
    # ### end Alembic commands ###
