"""add_action_id_to_notifications

Revision ID: f9048f9988ad
Revises: 7d911a4d04dc
Create Date: 2026-07-20 11:28:18.567973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9048f9988ad'
down_revision: Union[str, Sequence[str], None] = '7d911a4d04dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('action_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'action_id')
    # ### end Alembic commands ###
